### ISSUE TITLE
Fix deadlock when stopping the core RSA service

### ISSUE THREAD

**Issue by tcalmant** [tcalmant/ipopo#100]
When invalidating the RSA core component with remaining imported services (and maybe the same for exported services); a deadlock occurs in ``ImportRegistrationImpl.close()``.

This explains why most ([but not all](http://geekandpoke.typepad.com/geekandpoke/2012/09/simply-explained-concurrency.html)) Travis-CI runs were failing due to timeouts.

This issue must be fixed before releasing iPOPO 0.8.0.

**Comment by tcalmant** [comment]
Found the origin of the issue: ``self._executor.shutdown()`` call in ``Py4jContainer`` (``pelix/rsa/providers/distribution/py4j.py``) doesn't return.

A quick fix is to add ``False`` as argument to ``shutdown()`` to stop waiting for remaining threads.
(added soon on the ``rsa-integration`` branch).

I'll try to find what thread call blocks to fix the problem at its root.

**Comment by tcalmant** [comment]
The bug seems to be on [``osgiservicebridge``](https://github.com/ECF/Py4j-RemoteServicesProvider) side. A bug report will be posted there.
In the meantime, the issue is considered fixed on iPOPO side with the cdf267a commit.

**Comment by scottslewis** [comment]
Hi Thomas,

Do you have any more info on what the problem is with the osgiservicebridge shutdown? Pllease open at:  https://github.com/ECF/Py4j-RemoteServicesProvider/issues

Congrats on 0.8.0.

**Comment by tcalmant** [comment]
Hi Scott,

I'll work on the issue on Friday, I haven't been able to reproduce it on my
computer.

According to the code on the iPOPO side, it's a method given to the
ThreadPoolExecutor that blocks.
Therefore I suppose that the problem is related to async calls.

I'll create the issue when I'll start to work on it (I'll be abroad for 2
days)

Le mer. 22 août 2018 à 04:05, Scott Lewis <notifications@github.com> a
écrit :

**Comment by scottslewis** [comment]
Hi Thomas.

It seems that the karaf folks have just released 4.2.1, and so the 4.2.0 refs in the tutorial are out of date.  I've created this pull request to fix the tutorial doc:

https://github.com/tcalmant/ipopo/pull/102

Thanksinadvance.   Is there a way to refresh the readthedocs without doing a release?
