### ISSUE TITLE
AttributeError: 'Rest_API' object has no attribute '_RestDispatcher__routes'

### ISSUE THREAD

**Issue by LibertyWalk** [tcalmant/ipopo#104]
This error occurs when trying to access the url localhost:8886/api/v0.

Starting the HTTP-Server:

    for bundle in bundles_to_start:
        context.install_bundle(bundle).start()
        if bundle == 'pelix.services.eventadmin':
            with use_ipopo(context) as ipopo:
                ipopo.instantiate('pelix-services-eventadmin-factory', 'eventadmin', {})
        if bundle == 'rest_api_servlet':
            with use_ipopo(context) as ipopo:
                ipopo.instantiate('pelix.http.service.basic.factory', 'http-server', {
                    'pelix.http.address':'localhost',
                    'pelix.http.port':'8886'
                })

Servlet code:

    @ComponentFactory(name='rest_api_servlet_factory')
    @Provides(specifications='pelix.http.servlet')
    @Property('_path', 'pelix.http.path', '/api/v0')
    @Instantiate('rest_api_servlet')
    class Rest_API(RestDispatcher):
        """
        Simple servlet factory, uses a servlet
        """

        def __init__(self):
            self._path = None

        def bound_to(self, path, params):
            """
            Servlet bound to a path
            """
            print('Bound to ' + path)
            return True

        def unbound_from(self, path, params):
            """
            Servlet unbound from a path
            """
            print('Unbound from ' + path)
            return None

        @HttpGet("/list")
        def list_elements(self, request, response):
            response.send_content(200, "<p>The list</p>")

        @HttpPost("/form/<form_id:uuid>")
        def handle_form(self, request, response, form_id):
            response.send_content(200, "<p>Handled {}</p>".format(form_id))

        @HttpPut("/upload/<some_id:int>/<filename:path>")
        @HttpPut("/upload/<filename:path>")
        def handle_upload(self, request, response,some_id=None, filename=None):
            response.send_content(200, "<p>Handled {} : {}</p>".format(some_id, filename))

When I try to open localhost:8886/api/v0, this error occurs:

    Traceback (most recent call last):
    File "C:\Users\krennd\AppData\Local\Programs\Python\Python37\lib\site-packages\pelix\http\basic.py", line 304, in wrapper
        return getattr(servlet, name)(request, response)
    File "C:\Users\krennd\AppData\Local\Programs\Python\Python37\lib\site-packages\pelix\http\routing.py", line 250, in do_GET
        self._rest_dispatch(request, response)
    File "C:\Users\krennd\AppData\Local\Programs\Python\Python37\lib\site-packages\pelix\http\routing.py", line 299, in _rest_dispatch
        for route, method in self.__routes.get(http_verb, {}).items():
    AttributeError: 'Rest_API' object has no attribute '_RestDispatcher__routes'

Is that a bug? Or did I do something wrong here?

EDIT: Wrong class name

**Comment by tcalmant** [comment]
Hi,
The issue here is that you redefined `__init__()` without calling its parent implementation, which defines some members. This can be fixed by calling either `super(Rest_API, self).__init__()` or `RestDispatcher.__init__(self)`

You should have something like this:
```python
@ComponentFactory(name='rest_api_servlet_factory')
@Provides(specifications='pelix.http.servlet')
@Property('_path', 'pelix.http.path', '/api/v0')
@Instantiate('rest_api_servlet')
class Rest_API(RestDispatcher):
    """
    Simple servlet factory, uses a servlet
    """
    def __init__(self):
        super(Rest_API, self).__init__()
        self._path = None
# ...
```
