### ISSUE TITLE
i got an error, help me,how to

### ISSUE THREAD

**Issue by lpwwpl** [tcalmant/ipopo#115]
i download https://github.com/tcalmant/demo-ipopo-qt, and run,

i got an error:
    framework_uid = reference.get_property(pelix.remote.PROP_FRAMEWORK_UID)
AttributeError: module 'pelix.remote' has no attribute 'PROP_FRAMEWORK_UID'

how to clear the error

**Comment by tcalmant** [comment]
The property constant has been renamed `pelix.remote.PROP_ENDPOINT_FRAMEWORK_UUID` in order to match its OSGi counterpart.
