### ISSUE TITLE
ipopo still active?

### ISSUE THREAD

**Issue by scottslewis** [tcalmant/ipopo#123]
Hi Thomas.

Hope you are well.

Are you/anyone working on ipopo still?   I've had a crazy idea: How about contributing ipopo as part of an 'AI/Python tools for Eclipse/OSGi' project?

**Comment by tcalmant** [comment]
Hi Scott,
I'm doing well, thanks; hope you are too :)

Currently, I'm the only one working on iPOPO on my spare time, which is not as much as I'd like to 🫤 
I still have some work to do to release v3.0, compatible with the latest Python versions and a bit more friendly with completion assists in IDEs.

Contributing iPOPO to Eclipse could be a thing, it was already discussed a bit during some informal meetings at EclipseCon. The issue would be to find the right place for it. For example, OSGi would be nice but I don't know a lot of people that would contribute in Python there.

**Comment by scottslewis** [comment]
> Hi Scott, I'm doing well, thanks; hope you are too :)
> 
> Currently, I'm the only one working on iPOPO on my spare time, which is not as much as I'd like to 🫤 I still have some work to do to release v3.0, compatible with the latest Python versions and a bit more friendly with completion assists in IDEs.

FWIW, In the Java<->Python remote services distribution provider:

https://github.com/ECF/Py4j-RemoteServicesProvider/tree/master

I use a python 'import hook' (pep-302) that allows Java services implementing this module resolver interface:

https://github.com/ECF/Py4j-RemoteServicesProvider/blob/master/bundles/org.eclipse.ecf.provider.direct/src/org/eclipse/ecf/provider/direct/ModuleResolver.java

to dynamically add and remove python packages from the python path.  The python side of this is implemented in the osgiservicebridge:

https://github.com/ECF/Py4j-RemoteServicesProvider/tree/master/python/osgiservicebridge

This is pretty cool IMHO as it allows python modules to be added and removed via (java) OSGi services. 

Here's some example python code:

https://github.com/ECF/Py4j-RemoteServicesProvider/blob/master/examples/org.eclipse.ecf.examples.importhook.main/src/run.py

If interested I would happily contribute this to ipopo or to some target project(s) at Eclipse, along with everything else in the Java<->Python remote services provider.

> 
> Contributing iPOPO to Eclipse could be a thing, it was already discussed a bit during some informal meetings at EclipseCon. The issue would be to find the right place for it. For example, OSGi would be nice but I don't know a lot of people that would contribute in Python there.

Well, my initial thought would be to the runtime top-level project at eclipse (where Equinox, ECF, and other projects live).  I would be able to provide some maintenance/support for both Java and Python components, but we would/will need more than just me.   I brought this up in an email to the rt-pmc mailing list today.

**Comment by tcalmant** [comment]
Hi Scott,

The iPOPO v3 release is stuck due to some issues with the remote services tests, mostly timing issues but I also have issues with the Karaf setup for the Py4J tests.
It would be helpful if you could take a look at the v3 branch regarding the RSA implementation and tests.

V3 drops support of older Python versions and adds type hints everywhere possible.
I still have to make sure all tests pass, setup a new CI (using Docker in GitHub actions) and update the documentation.

Regarding the Eclipse Foundation, I might be able to attend OCX'24, which could be the place where to see how to set that up with people from the foundation.

**Comment by scottslewis** [comment]
Hi Thomas.

> 
> The iPOPO v3 release is stuck due to some issues with the remote services tests, mostly timing issues but I also have issues with the Karaf setup for the Py4J tests. It would be helpful if you could take a look at the v3 branch regarding the RSA implementation and tests.

I will take a look, but would like more info:  What do you mean 'stuck'?  Failing tests?  Deadlock (timing issues?).   And Karaf setup?  What's going wrong there?

> 
> V3 drops support of older Python versions and adds type hints everywhere possible. I still have to make sure all tests pass, setup a new CI (using Docker in GitHub actions) and update the documentation.
> 
> Regarding the Eclipse Foundation, I might be able to attend OCX'24, which could be the place where to see how to set that up with people from the foundation.

FWIW, I would not depend upon the Eclipse Foundation for anything in the way of support for ipopo as a (e.g.) new 'AI runtime' project...unless you already have a new or old corporate member lined up to sponsor (for releng, maintenance, integration such as RSA, new features, ipopo tooing, etc).

**Comment by tcalmant** [comment]
> What do you mean 'stuck'? Failing tests? Deadlock (timing issues?).

Mostly failing tests; I'm having some issues understanding if it comes from the libraries being outdated, their behaviour on Windows, ...

> And Karaf setup? What's going wrong there?

The Py4J bridge relies on Karaf for its tests, but
* v4.2.x/v4.3.x starts, but the feature-add command is not available. Apparently, it's due to Felix not being able to load some bundles with invalid Manifest
* v4.4.x starts but can't install the ecf feature, apparently due to non-HTTPS URLs

**Comment by scottslewis** [comment]
For the Karaf setup.   Long story:  Eclipse removed all http urls (in favor of https) and I've not yet gotten the Karaf folks to update their configuration files for the 'ecf' name for the feature:repo-add ecf command.  See issue #124 .  Submitted pr #125 for fix.

With regard to etcd.  Etcd2 has been effectively replaced by etcd3, and so I have to update the library that the etcd discovery provider used from etcd to one of the etcd3 python clients.   To do that I have to do a little bit of evaluation of the replacements and might have to rewrite some of the etcd discovery provider, so I've opened issue #126

**Comment by scottslewis** [comment]
Hi Thomas.  For your information, I've written this proposal to the osgi-technology mailing list at Eclipse Foundation:

https://www.eclipse.org/lists/osgi-technology-dev/msg00035.html

In a response to questions, I brought up the python rsa implementation in ipopo (which is wider than the py4j distribution provider only, as you know).

https://www.eclipse.org/lists/osgi-technology-dev/msg00037.html

**Comment by scottslewis** [comment]
Hi Thomas.  I've looked into the etcd v3 client and commented here

https://github.com/tcalmant/ipopo/issues/126#issuecomment-2219146812

Summary:  Haven't fully decided yet, but it may be easier to just implement a new etcdv3 discovery provider, as etcdv3 is implemented via protobuffers, and so much of the python classes can be generated via protoc of the .proto files (available directly from the etcdv3 server github project).

I also may do a little bit of hacking to see if the etcdv2 client can be gotten running in the interim...with an etcdv2 server.

**Comment by scottslewis** [comment]
Hi Thomas.

I was able to get and install a version of etcd v2.3.8 (uses old v2 protocol) from here:

https://github.com/etcd-io/etcd/releases?q=v2.3&expanded=true

After installing and running with this linux command line:

$./etcd -data-dir datadir

I was able to run successfully the etcd_discovery test in tests/rsa/test_etcd_discovery

I think that this should get you going wrt the v3 branch.   I'll begin work on the etcd v3 discovery provider impl in a new subpackage (probably discovery_etcd3.py)

I'm closing this issue then.  Thanks.

**Comment by tcalmant** [comment]
Hi Scott
From what I understand, it is possible to use RSA with etcd2, but it is required to have an etcd3 version ready for future work, am I right?

**Comment by scottslewis** [comment]
> Hi Scott From what I understand, it is possible to use RSA with etcd2, but it is required to have an etcd3 version ready for future work, am I right?

Yes.  The current implementation of the etcd discovery provider uses the etcd python client, which uses the etcd v2 server (that I link to above version 2.3.8).   So with an etcd v2 server, the existing provider will provide RSA endpoint description discovery right now.   I think there is a sample/example ipopo app for this right now.  With etcd v2 server it should just work.

What etcd did when it went from v2 to v3 was that it changed from using 'http rest' to grpc (Google RPC) for client->server interaction...as well as a bunch of server-side features, clustering and failover built in, etc.   Google RPC (based upon pprotocol buffers) is far more efficient object serialization, uses http2 (and has pluggable transports), more auth security and flexibility, scaling capacity, etc., etc.  This is really important for Google's cloud strategy as etcd is the discovery system/protocol for Kubernetes.

The move to v3/grpc on server-side, however, means that the client API is very different...and as I mention above it doesn't look like a lot of folks have *maintained and continued to improve* the etcd3 python clients.   Also, since grpc generates code from a proto file, much of a v3 client can simply be generated using the latest set of etcd protofiles (available on etcd repo).  That's essentially what I did with the java etcdv3 discovery provider....along with the 'wrapper' code for turning it into a proper ECF discovery provider.   Now, I propose that I do a similar thing with the ipopo etcdv3 discovery provider:  1) use protoc to generate python code from the etcd protofiles; 2) Add the classes in functions in a new discovery provider discovery_etcdv3.  I can probably borrow much of the structure that's in discovery_etcd.py...and I know how to do this as I've done it several times before..

One nice thing about this approach is that then either one of the etcd2 and etcd3 discovery providers can run in a framework simply by using either the 2 or 3 bundle (or both)...and either/both of these can run alongside other discovery providers and *any* of the distribution providers.   That's the way it is now, actually, on the java/osgi side.

Make sense?  If not let me know what's not clear.
