### ISSUE TITLE
Add docker-friendly remote service discovery providers

### ISSUE THREAD

**Issue by tcalmant** [tcalmant/ipopo#72]
Multicast is not available on Docker networks, which means that most of built-in discovery services can't work on that kind of architecture.

The following providers could be interesting to handle this situation:
* Broadcast discovery (this might work on Docker)
* Key-Value servers (ZooKeeper, Redis, ...) discoveries
  * based on hostnames
  * based on all available IPs, with a Framework UUID check on each IPs
* File-based discovery (requires static host names or IPs and a static binding port)

- [x] Redis discovery
- [x] Zookeeper discovery

**Comment by debbabi** [comment]
+1

**Comment by tcalmant** [comment]
Added ZooKeeper discovery in commit d31c4150a3781ff733e40f2628dc59d301d406e7
All feedback is welcome.

**Comment by tcalmant** [comment]
Tests added this week, leading to some fixes for compatibility with Python 2.7.
Considering this task done.
