### ISSUE TITLE
Provide a shortcut to do "install + start"

### ISSUE THREAD

**Issue by matthieucan** [tcalmant/ipopo#91]
In the Pelix shell, I often find myself running `install foo` and `start bar`, `bar` being the bundle id of `foo`. A command to install+start would surely be useful!

**Comment by tcalmant** [comment]
Agreed, as it could also be easily implemented:
* if the argument of ``start`` is an integer, then its a bundle ID (bundle names can't start with a digit)
* else, it's a bundle name, and we can do ``install+start``

**Comment by tcalmant** [comment]
Fixed.
You can now use both methods:

```
$ install pelix.http.basic
Bundle ID: 14
$ start $?
Starting bundle 14 (pelix.http.basic)...
```
and

```
$ start pelix.http.basic
Bundle ID: 14
Starting bundle 14 (pelix.http.basic)...
```

**Note:** The ``$?`` variable is not set by ``start`` as it accepts multiple IDs at once.
It is therefore recommended to use ``install`` in init scripts if you want to keep track of bundle IDs.

**Comment by matthieucan** [comment]
Wow, that was fast :) Thanks a lot!

**Comment by tcalmant** [comment]
Some tests must be updated after this change
